[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-graphql = { version = "7.0", optional = true }

[features]
default = []
backend = ["async-graphql"]